version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$USER
      - MONGO_INITDB_ROOT_PASSWORD=$PASSWORD

  worker:
    build: .
    command: celery -A app.core.celery_config worker -l INFO
    volumes:
      - ./:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - app
      - redis

  redis:
    image: redis
    restart: on-failure

volumes:
  mongo-data:
