version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    command: python main.py

  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27018:27017
    volumes:
      - mongo-data:/data/database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$USER
      - MONGO_INITDB_ROOT_PASSWORD=$PASSWORD

volumes:
  mongo-data:
