version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase
    command: python main.py

  db:
    image: mongo
    restart: always
    volumes:
      - ./db_data:/data/db

